---

- name: KVM | Install packages
  apt: 
    pkg: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - libvirt-bin    
    - qemu-kvm    
    - virt-manager
    - python-libvirt 
    - bridge-utils    
    - debootstrap



- name: KVM | Add admin to kvm-group
  user: 
    name: '{{ ansible_ssh_user }}'
    groups: libvirt
    append: yes 
