---

- name: check file
  stat: 
    path: '/var/lib/libvirt/images/vm-{{vm_name}}.qcow2'
  register: hdd_file
  tags: hdd


- include: clone_hdd.yml
  tags: hdd
  when: hdd_file.stat.exists == False


- include: create_vm.yml
  tags: vm
  when: not vm_update


- include: update_vm.yml
  tags: vm
  when: vm_update
